steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/akhil-ghatiki/dlp-rdb-bq-import.git']
    id: 'check-out-source-code'
  - name: gcr.io/cloud-builders/gradle:5.6.2-jdk-8
    args: ['assemble']
    dir: 'dlp-rdb-bq-import'
    id: 'build-jar'
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', '*bundled*.jar', 'gs://spike_oesc/build/dataflow_deployment_$BUILD_ID.jar']
    dir: 'dlp-rdb-bq-import/target'
    id: 'deploy-jar'
#  - name: gradle:5.6.2-jdk8
#    entrypoint: gradle
#    args: ["assemble"]